version: "2"
services:
  mysql:
    image: mariadb
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=phpservermon
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=test
    ports:
      - "8080:80"

  phpservermon:
    build: .
    container_name: phpservermon
    depends_on:
      - mysql
    environment:
      - PSM_BASE_URL=""
      - PSM_DB_HOST=mysql
      - PSM_DB_NAME=phpservermon
      - PSM_DB_USER=root
      - PSM_DB_PASS=test
      - PSM_DB_PREFIX=""
      - UPDATE_INTERVAL=15
    ports:
      - "8081:80"
