version: "2"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
    expose:
      - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=test
    container_name: phpmyadmin
    ports:
      - "8080:80"

  phpservermon:
    build: ./
    container_name: phpservermon
    environment:
      - PSM_BASE_URL=""
      - PSM_DB_HOST=mysql
      - PSM_DB_NAME=phpservermon
      - PSM_DB_USER=root
      - PSM_DB_PASS=test
      - PSM_DB_PREFIX=""
      - UPDATE_INTERVAL=15
    ports:
      - "8081:80"
